"""
M1 Cortical Column Network Model
=================================
Class-based implementation following the Potjans & Diesmann (2014) style.

Typical usage
-------------
>>> net = M1Network(neuron_type='LIF', connection_type='random')
>>> net.create_nodes()
>>> net.connect()
>>> net.create_bg_input()
>>> net.create_recorders()
>>> net.simulate()
>>> net.save_data()

The public attributes ``nodes``, ``spike_recorders``, and
``spatial_locations`` are available after the corresponding build step
for downstream use (e.g. plotting).
"""

import glob
import os

import nest
import numpy as np
import pandas as pd

import parameters as params


class M1Network:
    """
    M1 spiking neuron network model implemented in NEST.

    Parameters
    ----------
    neuron_type : str
        Neuron model to use. Currently supports ``'LIF'`` (``iaf_psc_exp``).
    connection_type : str
        Connectivity rule. ``'random'`` uses ``fixed_total_number`` drawn
        from Peter's Rule; ``'local'`` is reserved for distance-dependent
        connectivity (not yet implemented).
    conn_table_path : str
        Path to the space-delimited connection table CSV.

    Attributes
    ----------
    nodes : dict[str, list[NodeCollection]]
        Per-column neuron populations keyed by layer name (e.g. ``'2/3E'``).
        Each value is a list of NodeCollections, one per cortical column.
        Available after :meth:`create_nodes`.
    spike_recorders : dict[str, NodeCollection]
        Spike recorder devices keyed by layer name.
        Available after :meth:`create_recorders`.
    bg_generators : dict[str, NodeCollection]
        Background Poisson generators keyed by layer name.
        Available after :meth:`create_bg_input`.
    spatial_locations : dict[str, list[tuple]]
        3-D ``(x, y, z)`` positions for every neuron in each layer
        (µm units).  Available after :meth:`create_nodes`.
    """

    def __init__(
        self,
        neuron_type: str = "LIF",
        connection_type: str = "random",
        conn_table_path: str = "code/connection_table.csv",
    ) -> None:
        self.neuron_type = neuron_type
        self.connection_type = connection_type
        self.conn_table = pd.read_csv(conn_table_path, delimiter=" ", index_col=False)

        # Populated by the build methods below
        self.nodes: dict = {}
        self.spike_recorders: dict = {}
        self.bg_generators: dict = {}
        self.spatial_locations: dict = {}

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _z_boundaries(self, Z_range: int = 2300) -> list:
        """
        Return z-axis boundaries for cortical layer pairs (µm).

        Boundaries are proportional to the total neuron count in each
        E/I pair and are fully deterministic — no random numbers are drawn.

        Parameters
        ----------
        Z_range : int
            Total cortical depth (µm).

        Returns
        -------
        list[float]
            ``len(layers_name) // 2 + 1`` boundary values starting at 0.
        """
        boundaries = [0.0]
        total = sum(params.n_layer)
        for i in range(0, len(params.layers_name), 2):
            n_pair = params.n_layer[i] + params.n_layer[i + 1]
            boundaries.append(boundaries[-1] + n_pair / total * Z_range)
        return boundaries

    @staticmethod
    def _clean_val(val) -> float:
        """Strip unit suffix from a connection-table entry (``'87.8*pA'`` → ``87.8``)."""
        if isinstance(val, str):
            return float(val.split("*")[0])
        return float(val)

    # ------------------------------------------------------------------
    # Build methods
    # ------------------------------------------------------------------

    def create_nodes(
        self,
        X_range: int = 300,
        Y_range: int = 300,
        Z_range: int = 2300,
        spacing: int = 50,
    ) -> None:
        """
        Create spatially distributed neuron populations for each layer.

        Neuron positions are generated by NEST's internal RNG via
        ``nest.spatial.free`` with per-dimension ``nest.random.uniform``
        distributions.  Because NEST coordinates its RNG state across all
        virtual processes, this approach is safe for parallel (MPI)
        simulations — unlike calling an external generator such as
        ``numpy.random`` independently on each rank.

        For each layer/column tile the layout is:

        * **x** ~ Uniform[col_x_offset, col_x_offset + X_range]
        * **y** ~ Uniform[col_y_offset, col_y_offset + Y_range]
        * **z** ~ Uniform[z_min, z_max]  (layer-pair sub-band)

        Column tiles are arranged on a ``√num_cols × √num_cols`` grid
        with ``spacing`` µm gaps.  After all populations are created,
        :attr:`spatial_locations` is populated by querying NEST directly
        via ``nest.GetPosition``.

        Parameters
        ----------
        X_range, Y_range : int
            Width / depth of one column tile (µm).
        Z_range : int
            Total cortical depth (µm).
        spacing : int
            Gap between adjacent column tiles (µm).
        """
        print("Creating neuron populations with NEST-generated positions…")

        z_bounds = self._z_boundaries(Z_range)
        dim = int(np.sqrt(params.num_cols))

        for i, layer_name in enumerate(params.layers_name):
            num_neurons = params.n_layer[i]
            layer_pos = i // 2
            z_min = z_bounds[layer_pos]
            z_max = z_bounds[layer_pos + 1]

            self.nodes[layer_name] = []
            for col in range(params.num_cols):
                col_x = float((col % dim) * (X_range + spacing))
                col_y = float((col // dim) * (Y_range + spacing))

                # Per-dimension uniform distributions — drawn by NEST's
                # internal RNG, consistent across all MPI ranks.
                positions = nest.spatial.free(
                    [
                        nest.random.uniform(min=col_x,            max=col_x + X_range),
                        nest.random.uniform(min=col_y,            max=col_y + Y_range),
                        nest.random.uniform(min=z_min,            max=z_max),
                    ]
                )

                if self.neuron_type == "LIF":
                    col_nc = nest.Create(
                        "iaf_psc_exp",
                        n=num_neurons,
                        params=params.neuron_params_LIF,
                        positions=positions,
                    )
                else:
                    raise ValueError(
                        f"Unsupported neuron type '{self.neuron_type}'. "
                        "Currently only 'LIF' is implemented."
                    )
                
                self.nodes[layer_name].append(col_nc)
            
            print(f"  Layer '{layer_name}': {num_neurons * params.num_cols} neurons.")

        # Retrieve the positions NEST assigned so downstream code
        # (e.g. plotting) can access them without re-running NEST.
        for layer_name in params.layers_name:
            pos = []
            for nc in self.nodes[layer_name]:
                pos.extend(nest.GetPosition(nc))  # GetPosition returns a list
            self.spatial_locations[layer_name] = pos

        print("Neuron populations created.\n")

    def connect(self) -> None:
        """
        Build recurrent synapses between layer pairs from the connection table.

        Synapse counts are derived from Peter's Rule:

        .. math::

            N_{syn} = \\frac{\\ln(1-P_{max})}{\\ln\\left(1 - \\frac{1}{N_{src}\\,N_{tgt}}\\right)}

        Weights and delays are drawn from normal distributions with the
        mean and standard deviation specified in the connection table.
        """
        print(f"Building synaptic connectivity ({self.connection_type})…")

        for _, row in self.conn_table.iterrows():
            src_key = f"{row['Source']}{row['SourceType']}"
            tgt_key = f"{row['Target']}{row['TargetType']}"

            src_cols = self.nodes[src_key]
            tgt_cols = self.nodes[tgt_key]

            p_max = row["Pmax"]
            if p_max == 0:
                continue

            weight_mean = self._clean_val(row["Weight"])
            weight_std  = self._clean_val(row["Wstd"])
            delay_mean  = float(row["Delay"])
            delay_std   = float(row["Dstd"])

            if self.connection_type == "random":
                total_synapses = 0
                for src_nc in src_cols:
                    for tgt_nc in tgt_cols:
                        n_src = len(src_nc)
                        n_tgt = len(tgt_nc)
                        nsyn = int(
                            np.log(1.0 - p_max) / np.log(1.0 - 1.0 / (n_src * n_tgt))
                        )
                        conn_spec = {
                            "rule": "fixed_total_number",
                            "N": nsyn,
                            "allow_multapses": True,
                            "allow_autapses": False,
                        }
                        syn_spec = {
                            "synapse_model": "static_synapse",
                            "weight": nest.random.normal(
                                mean=weight_mean, std=weight_std
                            ),
                            "delay": nest.math.redraw(
                                nest.random.normal(mean=delay_mean, std=delay_std),
                                0.1,
                                100.0,
                            ),
                            "receptor_type": 0,
                        }
                        nest.Connect(src_nc, tgt_nc, conn_spec, syn_spec)
                        total_synapses += nsyn
                print(
                    f"  {src_key} → {tgt_key}: {total_synapses} synapses "
                    f"({len(src_cols)}×{len(tgt_cols)} column pairs)"
                )

            elif self.connection_type == "local":
                # Distance-dependent connectivity — to be implemented
                raise NotImplementedError(
                    "Local (distance-dependent) connectivity is not yet implemented."
                )

        print("Synaptic connectivity built.\n")

    def create_bg_input(self) -> None:
        """
        Create Poisson background generators and connect one to each layer.

        The firing rate for layer *i* is ``bg_freq x bg_layer[i]``.
        Generators are stored in :attr:`bg_generators`.
        """
        print("Creating background input…")

        for i, layer_name in enumerate(params.layers_name):
            rate = params.bg_freq * params.bg_layer[i]
            bg = nest.Create("poisson_generator", params={"rate": rate})
            for col_nc in self.nodes[layer_name]:
                nest.Connect(
                    bg,
                    col_nc,
                    syn_spec={"weight": params.w_ex, "delay": params.d_ex},
                )
            self.bg_generators[layer_name] = bg
            print(f"  Layer '{layer_name}': background rate = {rate:.1f} Hz")

        print("Background generators connected.\n")

    def create_recorders(self) -> None:
        """
        Create spike recorders and connect them to every layer.

        Recorder labels are derived from layer names with ``'/'`` removed
        (e.g. ``'2/3E'`` → ``'spikes_23E'``) to produce valid file names.
        Recorders are stored in :attr:`spike_recorders`.
        """
        print("Creating spike recorders…")

        for layer_name in params.layers_name:
            label = "spikes_" + layer_name.replace("/", "")
            sr = nest.Create(
                "spike_recorder",
                params={"record_to": "ascii", "label": label},
            )
            for col_nc in self.nodes[layer_name]:
                nest.Connect(col_nc, sr)
            self.spike_recorders[layer_name] = sr
            print(f"  Recorder '{label}' connected to '{layer_name}'")

        print("Spike recorders connected.\n")

    def simulate(self) -> None:
        """Run the NEST simulation for ``params.simulation_time`` ms."""
        print(f"Simulating for {params.simulation_time} ms…")
        nest.Simulate(params.simulation_time)
        print("Simulation complete.\n")

    def save_data(
        self, data_path: str = "data", data_prefix: str = "m1_"
    ) -> None:
        """
        Merge per-process spike files written by NEST into one CSV per layer.

        NEST writes one ``.dat`` file per recorder per MPI process.  This
        method concatenates all files for each layer, sorts by spike time,
        writes a single ``combined_spikes_<layer>.csv``, and removes the
        originals.

        Parameters
        ----------
        data_path : str
            Directory where NEST wrote the ``.dat`` files (must match
            ``nest.data_path``).
        data_prefix : str
            File-name prefix used by NEST (must match ``nest.data_prefix``).
        """
        print("Processing spike data…")
        layer_labels = [ln.replace("/", "") for ln in params.layers_name]

        for label in layer_labels:
            pattern = os.path.join(
                data_path, f"{data_prefix}spikes_{label}-*.dat"
            )
            spike_files = glob.glob(pattern)

            if not spike_files:
                print(f"  No spike files found for layer '{label}'.")
                continue

            dfs = [
                pd.read_csv(
                    f, sep=r"\s+", skiprows=3, names=["sender", "time_ms"]
                )
                for f in spike_files
            ]
            combined = pd.concat(dfs, ignore_index=True)
            combined.sort_values(by="time_ms", inplace=True)

            out_path = os.path.join(
                data_path, f"combined_spikes_{label}.csv"
            )
            combined.to_csv(out_path, index=False)
            print(
                f"  '{label}': merged {len(spike_files)} file(s) → {out_path}"
            )

            for f in spike_files:
                os.remove(f)

        print("Data processing complete.\n")
